### ISSUE TITLE
视频长度限制问题

### ISSUE THREAD

**Issue by heydoer** [Insfgg99x/FGVideoEditor#1]
1、视频长度限制默认适配为10s，当超过该时长，编辑页面的最大长度仍为10s，slider没有做适配
2、当视频长度超过maxDuration时候，拖动底部帧图片时候，会因为被overlay view阻断拖动事件，scrollview无法滚动，导致需要将overlay两边拉回一点，才可以从overlay外部拖动scrollview，体验不好

**Comment by Insfgg99x** [comment]
你好，问题已修复
//MARK: - 滑动事件过滤
extension FGVideoCropOverlay {
    override func hitTest(_ point: CGPoint, with event: UIEvent?) -> UIView? {
        let right = Int(bounds.size.width)
        let range = 15
        let x = Int(point.x)
        if (0...range).contains(x) || ((right - range)...right).contains(x) {
            return super.hitTest(point, with: event)
        }
        return nil
    }
}
